# GitHub Actions Workflow: Flight Price Tracker

name: Flight Price Tracker Automation

on:
  # 1. Scheduled Run: Runs automatically at 07:00 and 19:00 UTC.
  # This corresponds to 10:00 AM and 10:00 PM in Turkey Time (UTC+3).
  schedule:
    - cron: '0 7,19 * * *'
  
  # 2. Manual Trigger: Allows you to run the workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build-and-run:
    # The type of virtual machine the job will run on
    runs-on: ubuntu-latest
    
    # PERMISSION FIX: Grant the workflow write permissions to commit changes.
    permissions:
      contents: write

    steps:
      # 1. Step: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Step: Sets up a Python environment for use in actions.
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Step: Installs the Python libraries required by the script.
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Step: Installs the necessary browsers for Playwright.
      - name: Install Playwright Browsers
        run: playwright install --with-deps

      # 5. Step: Runs the main Python script.
      # The email password is securely passed as an environment variable from GitHub Secrets.
      - name: Run Flight Scraper and Analyzer
        env:
          MAIL_SIFRESI: ${{ secrets.MAIL_SIFRESI }}
        run: python flight_automation.py

      # 6. Step: Commits the updated archive file back to the repository.
      - name: Commit Updated Archive File
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated Archive Update: previous_results.csv'
          file_pattern: 'previous_results.csv error_screenshot.png'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Actions Bot <actions@github.com>'
